platform :ios, '9.0'
use_frameworks!
target 'FXHDemo' do
pod 'SDWebImage', '~> 4.3.3'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJExtension', '~> 3.0.13'
pod 'Masonry', '~> 1.0.1'
pod 'Alamofire', '~> 4.5.0'
pod 'MJRefresh', '~> 3.1.12'
end
